// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*) FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    original_url,
    short_name
) VALUES (
    $1, $2
) RETURNING id, original_url, short_name, created_at, updated_at
`

type CreateLinkParams struct {
	OriginalUrl string `json:"originalUrl"`
	ShortName   string `json:"shortName"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, created_at, updated_at FROM links
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLink(ctx context.Context, id int32) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, created_at, updated_at FROM links
WHERE short_name = $1 LIMIT 1
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_name, created_at, updated_at FROM links
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET 
    original_url = COALESCE($1, original_url),
    short_name = COALESCE($2, short_name),
    updated_at = NOW()
WHERE id = $3
RETURNING id, original_url, short_name, created_at, updated_at
`

type UpdateLinkParams struct {
	OriginalUrl pgtype.Text `json:"originalUrl"`
	ShortName   pgtype.Text `json:"shortName"`
	ID          int32       `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink, arg.OriginalUrl, arg.ShortName, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
